<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Armas extends Model
{
    //public $timestamps = false;

    public function  generarDatosArmas(){

        $armas=[];

                $arma =new Armas();
                $arma->codigo=59;
                $arma->nombre='Motor Químico';
                $arma->descripcion='El motor básco de cualquier cohete, proporciona un empuje constante alimentado por la combustión de propulsores';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=3;
                $arma->clase=3;
                $arma->niveltec=0;
                $arma->malcance=5;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=60;
                $arma->nombre='Motor nuclear';
                $arma->descripcion='Los motores nucleares nos dan la primera oportunidad de viajar a otras estrellas en un tiempo razonable.';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=4;
                $arma->clase=12;
                $arma->niveltec=0;
                $arma->malcance=5;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=61;
                $arma->nombre='Motor iones';
                $arma->descripcion='Los nuevos avances tecnoloógicos nos premiten crar un codigo de motor muy ligero y rápido como alternativa al motor nuclear.';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=5;
                $arma->clase=13;
                $arma->niveltec=1;
                $arma->malcance=5;
                $arma->dispersion=4;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=62;
                $arma->nombre='Motor de plasma';
                $arma->descripcion='Los motores de plasma son mucho mas caros de construir y mantener, peligrosos si son dañados en un combate y además complicados de hacer. Sin embargo podemos obtener unas velocidades muy altas y una cantidad de energía enorme muy util para montar tod';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=5;
                $arma->clase=14;
                $arma->niveltec=2;
                $arma->malcance=10;
                $arma->dispersion=6;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=63;
                $arma->nombre='Motor MA';
                $arma->descripcion=' No se conoce fuente de energía mas compacta que la antimateria, podemos crear sistemas de propulsión basados en ella como combustible en combinación con nuestros conocimientos en otros propulsores.';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=10;
                $arma->clase=15;
                $arma->niveltec=10;
                $arma->malcance=10;
                $arma->dispersion=8;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=64;
                $arma->nombre='Motor HMA';
                $arma->descripcion=' La energía que podemos extraer de la antimateria es tan enorme que es posible crear un pliegue en el espacio-tiempo de tal forma que se puede viajar entre dos puntos distantes en un instante.';
                $arma->jugadores_id=1;
                $arma->ranura="motores";
                $arma->potencia=10;
                $arma->clase=16;
                $arma->niveltec=5;
                $arma->malcance=5;
                $arma->dispersion=5;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=65;
                $arma->nombre='Titanio N';
                $arma->descripcion='El Titanio N es un blindaje especial para naves espaciales, pese a su elevado peso da una protección excelente frente a impactos y armas energéticas';
                $arma->jugadores_id=1;
                $arma->ranura="blindajes";
                $arma->potencia=13;
                $arma->clase=10;
                $arma->niveltec=2;
                $arma->malcance=4;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=66;
                $arma->nombre='Reactivo N';
                $arma->descripcion='El blindaje reactivo combina la resistencia de un blindaje de Titanio N con una gran durabilidad frente a detonaciones';
                $arma->jugadores_id=1;
                $arma->ranura="blindajes";
                $arma->potencia=15;
                $arma->clase=10;
                $arma->niveltec=4;
                $arma->malcance=3;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=67;
                $arma->nombre='Resinas A';
                $arma->descripcion='Mediante resinas metálicas autoendurecibles y expansivas logramos que tras un impacto cualquier brecha quede sellada al instante';
                $arma->jugadores_id=1;
                $arma->ranura="blindajes";
                $arma->potencia=9;
                $arma->clase=10;
                $arma->niveltec=8;
                $arma->malcance=5;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=68;
                $arma->nombre='Placas TAC';
                $arma->descripcion='Con una aleacion titanio-aluminio-carbono y tratamientos nanotecnologicos de templado obtenemos una material tremendamente duro, flexible y rápido de producir, aunque muy pesado y caro';
                $arma->jugadores_id=1;
                $arma->ranura="blindajes";
                $arma->potencia=15;
                $arma->clase=10;
                $arma->niveltec=11;
                $arma->malcance=6;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=69;
                $arma->nombre='Carbonadio';
                $arma->descripcion='Este material creado a partir de resinas, es la version moldeable de otro compuesto mucho ma caro y dificil de trabajar usado para piezas muy concretas de los motores M-A';
                $arma->jugadores_id=1;
                $arma->ranura="blindajes";
                $arma->potencia=30;
                $arma->clase=10;
                $arma->niveltec=15;
                $arma->malcance=8;
                $arma->dispersion=-60;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=70;
                $arma->nombre='Optimizador';
                $arma->descripcion='Podemos optimizar nuestros diseños empleando parte de la energía sobrante en ciertos sistema para reducir los costos';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=13;
                $arma->clase=7;
                $arma->niveltec=4;
                $arma->malcance=5;
                $arma->dispersion=-5;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=71;
                $arma->nombre='Escudos';
                $arma->descripcion='Combinando u campo elertromagnético y nanotecnología podemos bloquear parte del fuego enemigo';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=16;
                $arma->clase=7;
                $arma->niveltec=6;
                $arma->malcance=5;
                $arma->dispersion=5;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=72;
                $arma->nombre='Salvas';
                $arma->descripcion='Mediante el antiguo sistema de disparar munición falsa para corregir errores en los disparos verdaderos, podemos ahorrar munición';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=10;
                $arma->clase=7;
                $arma->niveltec=10;
                $arma->malcance=5;
                $arma->dispersion=10;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=73;
                $arma->nombre='Standartd';
                $arma->descripcion='Mediante el uso de piezas iguales en todas las naves podemos reducir considerablemente los gastos diarios de las naves';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=15;
                $arma->clase=7;
                $arma->niveltec=11;
                $arma->malcance=5;
                $arma->dispersion=7;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=74;
                $arma->nombre='Ctrl de puntería';
                $arma->descripcion='Estadisticamente podemos predecir las maniobras de cada codigo de nave y así poder mejorar la puntería de nuestras armas';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=0;
                $arma->clase=7;
                $arma->niveltec=7;
                $arma->malcance=2;
                $arma->dispersion=10;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=75;
                $arma->nombre='Aleaciones';
                $arma->descripcion='Incorporando aleaciones mas ligeras en las partes no vitales de las naves podemos reducir sensiblemente su peso, aunque para obtener las mismas prestaciones los costos son elevados';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=12;
                $arma->clase=7;
                $arma->niveltec=8;
                $arma->malcance=5;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=76;
                $arma->nombre='Baterias';
                $arma->descripcion='Almacenando parte de la energía obtenida durante los desplazamientos podemos usarla mas adelante durante los sistemas de armas';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=13;
                $arma->clase=7;
                $arma->niveltec=9;
                $arma->malcance=5;
                $arma->dispersion=10;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=77;
                $arma->nombre='Distribuidor';
                $arma->descripcion='Colocando esta mejora al final de todas reduce el costo de  todas las mejoras anteriores ya que las redistribuye dentro de la nave de la forma optima';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=13;
                $arma->clase=7;
                $arma->niveltec=3;
                $arma->malcance=10;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=78;
                $arma->nombre='Compactador';
                $arma->descripcion='La óptima distribución de la carga en una bodega puede mejorar de forma considerable la capacidad, esta mejora aumenta la carga por unidad';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=0;
                $arma->clase=7;
                $arma->niveltec=2;
                $arma->malcance=10;
                $arma->dispersion=30;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=79;
                $arma->nombre='Prop. maniobra';
                $arma->descripcion='Gran cantidad de combustible se va en las maniobras de atraque y reajuste de rumbo. Con pequeños motores químicos podemos reducir el gasto de los motores principales';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=1;
                $arma->malcance=2;
                $arma->dispersion=10;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=80;
                $arma->nombre='C. Nanos';
                $arma->descripcion='Podemos catalizar los procesos naníticos de producción de naves mejorando enormemente la velocidad de construcción';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=14;
                $arma->clase=7;
                $arma->niveltec=5;
                $arma->malcance=4;
                $arma->dispersion=10;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=81;
                $arma->nombre='Plegado';
                $arma->descripcion='Partes de las naves que queremos meter en los hangares pueden ser desmontadas o plegadas aumentando la capacidad disponible hasta un límite';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=13;
                $arma->clase=7;
                $arma->niveltec=12;
                $arma->malcance=2;
                $arma->dispersion=70;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=82;
                $arma->nombre='Ariete';
                $arma->descripcion='Con esta mejora podemos aumentar mucho el daño de las armas a corta distancia';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=3;
                $arma->malcance=2;
                $arma->dispersion=70;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=83;
                $arma->nombre='Foco';
                $arma->descripcion='Podemos mejorar el daño a las naves que mas daño queremos hacer ';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=4;
                $arma->malcance=2;
                $arma->dispersion=127;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=84;
                $arma->nombre='F-caza';
                $arma->descripcion='Con esta mejora nuestras armas a cazas realizan una predicción de posición de mas efectiva aumentando el daño a los cazas';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=13;
                $arma->malcance=2;
                $arma->dispersion=127;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=85;
                $arma->nombre='F-ligera';
                $arma->descripcion='Podemos aumentar el daño sólo a naves ligeras sin seguimos sus patrones de movimiento';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=14;
                $arma->malcance=2;
                $arma->dispersion=127;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=86;
                $arma->nombre='F-media';
                $arma->descripcion='Conociendo la estruictura de las naves medias es facil causar más daños, esto lo consigue esta mejora a bajo costo.';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=15;
                $arma->malcance=2;
                $arma->dispersion=127;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=87;
                $arma->nombre='F-pesada';
                $arma->descripcion='Causar más daño a pesadas no es sólo cuestión de potencia, esta mejora analiza sus puntos débiles.';
                $arma->jugadores_id=1;
                $arma->ranura="mejoras";
                $arma->potencia=8;
                $arma->clase=7;
                $arma->niveltec=16;
                $arma->malcance=2;
                $arma->dispersion=127;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=90;
                $arma->nombre='Contenedor de carga';
                $arma->descripcion='Módulo básico de carga, compuesto de un contenedor standard intercambiable';
                $arma->jugadores_id=1;
                $arma->ranura="cargaPequeña";
                $arma->potencia=20000;
                $arma->clase=9;
                $arma->niveltec=1;
                $arma->malcance=10;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=91;
                $arma->nombre='Vagón de carga';
                $arma->descripcion='Contenedor de carga ampliado y mejorado, con sistema de descarga rápido y enganche magnético';
                $arma->jugadores_id=1;
                $arma->ranura="cargaPequeña";
                $arma->potencia=40000;
                $arma->clase=9;
                $arma->niveltec=5;
                $arma->malcance=10;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=92;
                $arma->nombre='Bahia de carga';
                $arma->descripcion='Enorme sistema de carga con sistema de compresión incluido';
                $arma->jugadores_id=1;
                $arma->ranura="cargaMedia";
                $arma->potencia=200000;
                $arma->clase=9;
                $arma->niveltec=8;
                $arma->malcance=10;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=93;
                $arma->nombre='Gran hangar de carga';
                $arma->descripcion='Sistema mejorado de almacenamiento y distribucion robotizado';
                $arma->jugadores_id=1;
                $arma->ranura="cargaGrande";
                $arma->potencia=500000;
                $arma->clase=9;
                $arma->niveltec=14;
                $arma->malcance=10;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=94;
                $arma->nombre='Contenedor Adimensional';
                $arma->descripcion='Almacena la carga en un estado de indeterminación entre varios universos paralelos';
                $arma->jugadores_id=1;
                $arma->ranura="cargaGrande";
                $arma->potencia=1000000;
                $arma->clase=9;
                $arma->niveltec=23;
                $arma->malcance=10;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=97;
                $arma->nombre='Hangar';
                $arma->descripcion='Cada unidad de hangar da cabida para un caza';
                $arma->jugadores_id=1;
                $arma->ranura="cargaPequeña";
                $arma->potencia=1;
                $arma->clase=9;
                $arma->niveltec=3;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=98;
                $arma->nombre='Muelle naves ligeras';
                $arma->descripcion='Hangar de atraque para naves ligeras, cada uno da cabida para una nave ligera';
                $arma->jugadores_id=1;
                $arma->ranura="cargaMedia";
                $arma->potencia=1;
                $arma->clase=9;
                $arma->niveltec=12;
                $arma->malcance=0;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=99;
                $arma->nombre='Puerto naves medias';
                $arma->descripcion='Puerto para atracar naves medias, con todos los sistemas de reparacion y mantenimiento necesarios para 1 nave media';
                $arma->jugadores_id=1;
                $arma->ranura="cargaGrande";
                $arma->potencia=1;
                $arma->clase=9;
                $arma->niveltec=16;
                $arma->malcance=0;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=101;
                $arma->nombre='Bomba EM';
                $arma->descripcion='Mediante un pequeña detonación nuclear a gran altura, podemos generar un pulso electromagnético que funda todo codigo de circuitos y anule las defensas enemigas';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=500;
                $arma->clase=1;
                $arma->niveltec=2;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=102;
                $arma->nombre='Cañón Maser';
                $arma->descripcion='Al igual que se han mejorado los cañones laser, se ha conseguido un modelo de arma de laser de microondas (Maser) con todas las prestaciones de los modelos antiguos pero más daño por disparo, aunque modulado sólo a larga distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=300;
                $arma->clase=1;
                $arma->niveltec=3;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=103;
                $arma->nombre='Inyector energético';
                $arma->descripcion='Un pequeño misil porta laser que se dispara a corta distancia del objetivo, así la dispersion del laser se reduce y el daño es mayor, auqne solo es util contra objetivos medios no muy rápidos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=1000;
                $arma->clase=1;
                $arma->niveltec=4;
                $arma->malcance=0;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=104;
                $arma->nombre='Cañón de neutrones';
                $arma->descripcion='Emitiendo un haz de neutrones concentrado a modo de laser podemos causar grandes daños sobre naves distancias intermedias';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=500;
                $arma->clase=1;
                $arma->niveltec=5;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=105;
                $arma->nombre='Bomba termobárica';
                $arma->descripcion='Ideal para destruir bunkers y complejos defensivos, este arma consigue una intensa deflagración con efectos térmicos similares a un arma nuclear. El combustible que no se incendie queda como arma quimica';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=1000;
                $arma->clase=1;
                $arma->niveltec=6;
                $arma->malcance=1;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=106;
                $arma->nombre='Misil PEM';
                $arma->descripcion='Lanzando un misil con una pequeña cabeza nuclear y detonandolo en las proximidas del objetivo generamos un intenso pulso electromagnético que deshabilita los sistemas enemigos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=1000;
                $arma->clase=1;
                $arma->niveltec=7;
                $arma->malcance=0;
                $arma->dispersion=-2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=107;
                $arma->nombre='Laser UV';
                $arma->descripcion='Emitiendo un haz de energía en la banda ultravioleta podemos causar mucho mas daño que a frecuencias mas bajas';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=3500;
                $arma->clase=1;
                $arma->niveltec=8;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=108;
                $arma->nombre='Pulso de neutrones';
                $arma->descripcion='Generando una explosión de de neutrones y redirigiéndola mediante pantallas reflectantes creamos un pulso dirigido capaz de penetrar de blindaje espesos.';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=450;
                $arma->clase=1;
                $arma->niveltec=9;
                $arma->malcance=0;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=110;
                $arma->nombre='Batería turbolaser';
                $arma->descripcion='Equipados con un acumulador independiente lo que las hace claramente superiores a las anteriores de su categoría, tanto en precio como en daño.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=700;
                $arma->clase=1;
                $arma->niveltec=11;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=111;
                $arma->nombre='Proyector de neutrones';
                $arma->descripcion='Mediante una carga nuclear dirigida se emite un potente haz de neutrones de alta penetración, erradicando toda forma de vida y descomponiendo los materiales';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=5000;
                $arma->clase=1;
                $arma->niveltec=12;
                $arma->malcance=0;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=112;
                $arma->nombre='Misil de fusión inercial';
                $arma->descripcion='Este arma usa la tecnología balística para lanzar un misil a baja velocidad que en pleno vuelo se funde. Al chocar con su objetivo se adhire y corroe en minutos el blindaje.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=700;
                $arma->clase=1;
                $arma->niveltec=13;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=113;
                $arma->nombre='Laser C';
                $arma->descripcion='Combinando todos las tecnologías laser podemos crear un haz de pulsos variados de baja frecuencia que garantizen el daño en cualquier nave pequeña por deprisa que se mueva o defensa posea.';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=500;
                $arma->clase=1;
                $arma->niveltec=14;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=114;
                $arma->nombre='Doble cañón Maser';
                $arma->descripcion='Hemos mejorado el cañón Maser obtiendo dos emisores trabajando en paralelo amplificando sus ondas';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=400;
                $arma->clase=1;
                $arma->niveltec=15;
                $arma->malcance=1;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=115;
                $arma->nombre='Laser X';
                $arma->descripcion='Respondiendo a las necesidades actuales, podemos diseñar un arma pesada laser potencia elevada y muy bajo precio, aunque solo se puede montar en las naves más pesadas con espacio para ello.';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=7000;
                $arma->clase=1;
                $arma->niveltec=16;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=116;
                $arma->nombre='Pulso Gamma';
                $arma->descripcion='Emitiendo rayos gamma de alta penetración através de una detonación nuclear podemos neutralizar al enemigo en un amplio radio atravesando blindajes pesados y a larga distancia.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=800;
                $arma->clase=1;
                $arma->niveltec=17;
                $arma->malcance=1;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();

                $arma =new Armas();
                $arma->codigo=118;
                $arma->nombre='Proyector UV';
                $arma->descripcion='Respondiendo a las necesidades de armas más potentes para hacer frente a naves cada vez mayores, obtenemos un arma especializada contra densos blindajes, su gran poder de perforación se ve ensombrecido por su corto alcance y gran consumo';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=15000;
                $arma->clase=1;
                $arma->niveltec=19;
                $arma->malcance=-2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=119;
                $arma->nombre='Laser atómico';
                $arma->descripcion='Dominadas todas las formas de laser con las diferentes longitudes de onda, nuestros científicos pueden crear un haz laser que emita partículas de alta energía, aunque de corta vida. Ideal para montar en cantidad.';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=5000;
                $arma->clase=1;
                $arma->niveltec=20;
                $arma->malcance=1;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=120;
                $arma->nombre='Misil DDM';
                $arma->descripcion='Aplicando nuestros ultimos descubrimientos sobre la composición de la materia, podemos enviar un mecanismo que descomponga los blindajes enemigos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=1800;
                $arma->clase=1;
                $arma->niveltec=21;
                $arma->malcance=0;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=121;
                $arma->nombre='Mini laser X';
                $arma->descripcion='Reduciendo el tamaño de nuestros anteriores laser podemos obtener un arma muy barata aunque de poca potencia';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=800;
                $arma->clase=1;
                $arma->niveltec=22;
                $arma->malcance=-1;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=123;
                $arma->nombre='Cañon multifásico';
                $arma->descripcion='Podemos generar un haz de energias coherentes cuyas frecuencias se sumen de forma armónica para aumentar su potencia';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=16000;
                $arma->clase=1;
                $arma->niveltec=24;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=124;
                $arma->nombre='Generador AN';
                $arma->descripcion='Este arma induce el colapso del espacio-tiempo en un micro agujero negro temporal que devora cualquier materia';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=7500;
                $arma->clase=1;
                $arma->niveltec=25;
                $arma->malcance=0;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=125;
                $arma->nombre='Laser BEC';
                $arma->descripcion='Este arma dispara un condensado Bose-Einstein usando fotones que se amplifica en su recorrido hacia el objetivo';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=400;
                $arma->clase=1;
                $arma->niveltec=26;
                $arma->malcance=1;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=126;
                $arma->nombre='GravWave';
                $arma->descripcion='Con un potente campo magnético somos capaces de convertir ondas electromagnéticas en gravitatorias, aplastando bajo su propio peso al enemigo';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=4000;
                $arma->clase=1;
                $arma->niveltec=27;
                $arma->malcance=3;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=127;
                $arma->nombre='Ariete de energía';
                $arma->descripcion='Con una descarga masiva de energía proviniente de los sobproductos de los motores y acelerados magnéticamente, podemos causar grandes daños a bajo precio';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=1000;
                $arma->clase=1;
                $arma->niveltec=28;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=129;
                $arma->nombre='Misil multifásico';
                $arma->descripcion='Siguiendo la misma tecnología que el cañón multifásico, podemos acercar la fuente al objetivo mediante un misil, este modelo está pensado como complemento a otras armas';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=120;
                $arma->clase=1;
                $arma->niveltec=30;
                $arma->malcance=1;
                $arma->dispersion=4;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=130;
                $arma->nombre='Laser gamma';
                $arma->descripcion='Mediante un laser de rayos gamma podemos generar fusion nuclear explosiva en el mismo objetivo';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=5000;
                $arma->clase=1;
                $arma->niveltec=31;
                $arma->malcance=0;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=131;
                $arma->nombre='Laser superfluido';
                $arma->descripcion='Disparando un haz de luz superfluida obtenemos un gasto de energía muy bajo para grandes potencias y distancias';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=10000;
                $arma->clase=1;
                $arma->niveltec=32;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=132;
                $arma->nombre='Laser B-E';
                $arma->descripcion='Este arma dispara un condensado Bose–Einstein de fotones  de alta energía con una precisión increible';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=520;
                $arma->clase=1;
                $arma->niveltec=33;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=134;
                $arma->nombre='Lapa laser';
                $arma->descripcion='En un sistema similar a una mina este artefacto se dispara y adhiere al casco de las naves, pero en vez de detonar genera un laser de alta intensidad y cortisimo alcance que perfora el casco en minutos.';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=4500;
                $arma->clase=1;
                $arma->niveltec=35;
                $arma->malcance=1;
                $arma->dispersion=-1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=135;
                $arma->nombre='Red microondas';
                $arma->descripcion='Disparando una red de sondas alrededor del objetivo pueden generar un campo de microondas que caliente un area';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=500;
                $arma->clase=1;
                $arma->niveltec=36;
                $arma->malcance=1;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=136;
                $arma->nombre='Stiletto';
                $arma->descripcion='Unos campos magnéticos generado por una explosión nuclear propulsan un estrecho chorro de metal fundido que se metamorfosea en una bala aerodinámica durante el vuelo.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=2500;
                $arma->clase=1;
                $arma->niveltec=37;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=137;
                $arma->nombre='Cañón anafásico';
                $arma->descripcion='Emitiendo laser en frecuencias y amplitudes aleatorias en rápida sucesión conseguimos desastibilizar y penetrar cualquier codigo de blindaje';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=20000;
                $arma->clase=1;
                $arma->niveltec=38;
                $arma->malcance=0;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=139;
                $arma->nombre='Reflector R';
                $arma->descripcion='Este arma recoge todo codigo de radiacción de las contramedidas enemigas y la vuelve a emitir en forma concentrada en forma coherente';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=2000;
                $arma->clase=1;
                $arma->niveltec=40;
                $arma->malcance=0;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=140;
                $arma->nombre='Medusa';
                $arma->descripcion='Mediante un haz de energía podemos forzar  a los quarks que componen los átomos a acoplarse generando anomalias en críticas en los blindajes mas resistentes';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=9000;
                $arma->clase=1;
                $arma->niveltec=41;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=141;
                $arma->nombre='Haz inercial';
                $arma->descripcion='La cadencia de tiro de este arma es tal que barre por completo un area, ideal para objetivos rápidos cuando no importa la munición';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=2200;
                $arma->clase=1;
                $arma->niveltec=42;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=142;
                $arma->nombre='Conversor Quark';
                $arma->descripcion='Este arma proyecta un haz de quarks que desastibiliza la materia a nivel subatómico';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=2000;
                $arma->clase=1;
                $arma->niveltec=43;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=143;
                $arma->nombre='Proyector N';
                $arma->descripcion='Con la frecuencia adecuada podemos variar la fuerza nuclear que une los átomos de los elementos del blindaje de una nave, provocando su inestabilidad a nivel atómico.';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=22000;
                $arma->clase=1;
                $arma->niveltec=44;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=152;
                $arma->nombre='Cañón de plasma';
                $arma->descripcion='Podemos crear un pequeño emisor de plasma en forma de cañón, su alcance es limitado pero su cadencia de tiro es muy alta';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=200;
                $arma->clase=2;
                $arma->niveltec=1;
                $arma->malcance=-1;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=153;
                $arma->nombre='Pulso plasma';
                $arma->descripcion='Podemos aumentar la potencia de un cañon de plasma generando breves pero potentes emisiones de plasma, aunque su cadencia de tiro y movilidad son bajas su potencia merece la pena.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=500;
                $arma->clase=2;
                $arma->niveltec=2;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=155;
                $arma->nombre='Cañón 4P';
                $arma->descripcion='Si unimos 4 cañones de plasma mejorados en una sola plataforma para que disparen de forma alternada obtenemos un arma de muy altas prestaciones ideal contra naves pesadas.';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=5000;
                $arma->clase=2;
                $arma->niveltec=4;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=156;
                $arma->nombre='Bomba de plasma';
                $arma->descripcion='Una buena forma de destruir una estructura muy blindada es generar una explosion de plasma sobre ella, provocando un torrente de matera a altisima temperatura que fundira todo lo que toque inutizándola';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=700;
                $arma->clase=2;
                $arma->niveltec=5;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=157;
                $arma->nombre='Mini cañón de P.';
                $arma->descripcion='Este arma genera pequeñas descargas de plasma a altísima temperatura y las acelera magnéticamente, su cadencia es muy alta convirtiendola en ideal contra cazas';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=250;
                $arma->clase=2;
                $arma->niveltec=6;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=159;
                $arma->nombre='Lanzador MMP';
                $arma->descripcion='Una bateria de pequeños misiles guiados por laser son mas eficientes que uno que puede ser interceptado. Estos misiles se lanzan como un proyectil y a medio camino se autopropulsan, mejorando su alcance y su puntería';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=800;
                $arma->clase=2;
                $arma->niveltec=8;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=160;
                $arma->nombre='Torre de plasma';
                $arma->descripcion='Reduciendo el tamaño y sacrificando algunas prestaciones de las defensas de plasma podemos crear una estructura portable para naves, aunque algo tosca muy efectiva a corta distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=3000;
                $arma->clase=2;
                $arma->niveltec=9;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=161;
                $arma->nombre='Batería de plasma';
                $arma->descripcion='Ahora somos capaces de mejorar el alcance de nuestras armas de plasma y reduciendo el costo, pese a la bajada de potencia';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=100;
                $arma->clase=2;
                $arma->niveltec=10;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=162;
                $arma->nombre='Misil MPC';
                $arma->descripcion='Este misil se divide estalla segundos antes de llegar a su objetivo generando 6 esferas de plasma concentrado, ideal para alcanzar objetivos medios';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=300;
                $arma->clase=2;
                $arma->niveltec=11;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=163;
                $arma->nombre='Acelerador de plasma';
                $arma->descripcion='Podemos proyectar gran cantidad de plasma mediante un acelerador magnético, y aunque poco maniobrable nuestros militares sabrán darle un buen uso';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=13000;
                $arma->clase=2;
                $arma->niveltec=12;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=164;
                $arma->nombre='Cañon multiplasma';
                $arma->descripcion='Este arma dispara en rápida sucesión haces de plasma de diferentes codigos, asegurando la penetracion de cualquier blindaje a una buena distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=2500;
                $arma->clase=2;
                $arma->niveltec=13;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=166;
                $arma->nombre='Misil Vulcan';
                $arma->descripcion='Lanzando un generador de plasma de alta energía en la cabeza de un misil conseguimos un arma muy barata y manejable';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=2000;
                $arma->clase=2;
                $arma->niveltec=15;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=167;
                $arma->nombre='Acelerador Ambiplasma';
                $arma->descripcion='El ambiplasma es un plasma que contiene una mezcla de materia y antimateria debido a que sus partículas son demasiado calientes y de muy baja densidad no se aniquilan entre ellas rápidamente. Podemos crear un acelerador que lo proyecte';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=15000;
                $arma->clase=2;
                $arma->niveltec=16;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=168;
                $arma->nombre='Mini cañon multiplasma';
                $arma->descripcion='Miniaturizando nuestros descubrimientos actuales obtenemos un arma de bajo peso y altas prestaciones';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=300;
                $arma->clase=2;
                $arma->niveltec=17;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=169;
                $arma->nombre='Bomba ambiplasma';
                $arma->descripcion='Lanzando un productor de ambiplasma directamente sobre un objetivo podemos provocar gravísimos daños incluso a grán profundidad. Ademas tenemos la tecnología que permite mantenerla activa desde mayor distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=3000;
                $arma->clase=2;
                $arma->niveltec=18;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=170;
                $arma->nombre='Proyector plasma inercial';
                $arma->descripcion='Nuestros recientes investigaciones en balistica nos permiten combinarlas con la tesnología de plasma para obtener un arma temible';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=2000;
                $arma->clase=2;
                $arma->niveltec=19;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=171;
                $arma->nombre='Cañón ambiplasma';
                $arma->descripcion='Podemos mejorar las prestaciones de las anteriores armas de ambiplasma, como el ambiplasma está afectado por la condensación de ondas de gravedad y otras ondas de presión de radiación expansiva podemos prescindir de aceleradores para su emisión';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=6000;
                $arma->clase=2;
                $arma->niveltec=20;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=172;
                $arma->nombre='Misil Devastador';
                $arma->descripcion='Este misil genera un descarga de plasma a alta temperatura provocando una inmensa diferencia termica en los los blindajes';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=1700;
                $arma->clase=2;
                $arma->niveltec=21;
                $arma->malcance=1;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=173;
                $arma->nombre='Tormenta de plasma';
                $arma->descripcion='Polarizando las partículas solares que se proyectan de manera natural y emitiendolas en forma de nube podemos envolver naves lentas provocando daños sobre todos sus sistemas';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=8500;
                $arma->clase=2;
                $arma->niveltec=22;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=175;
                $arma->nombre='Cañón C-Plasma';
                $arma->descripcion='En vez de emitir pulsos de plasma, este arma genera un fino chorro continuo que garantiza precisión a largo alcance';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=500;
                $arma->clase=2;
                $arma->niveltec=24;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=176;
                $arma->nombre='Campo de Plasma';
                $arma->descripcion='Generando un campo energético mediante una corriente de plasma, podemos romper los enlaces de las moléculas de carbono y así deshacer la mayoría de los blindajes';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=2500;
                $arma->clase=2;
                $arma->niveltec=25;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=177;
                $arma->nombre='Proyector L-plasma';
                $arma->descripcion='Para evitar la pérdida de potencia del plasma hasta llegar a su objetivo, este arma emite un tubo laser dentro del cual se dispara el plasma minimizando las pérdidas de temperatura';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=4000;
                $arma->clase=2;
                $arma->niveltec=26;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=178;
                $arma->nombre='Emisor Plasma SS';
                $arma->descripcion='Un torrente de plasma supermasivo disparado a velocidades sublumínicas se comporta como una Supercuerda alterando el mismo espacio-tiempo dañando el objetivo aunque no lo toque.';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=7000;
                $arma->clase=2;
                $arma->niveltec=27;
                $arma->malcance=3;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=179;
                $arma->nombre='Cartuchos Plasma';
                $arma->descripcion='Este arma de largo alcance dispara una infinidad de pequeñas bolas de plasma sobre un area asegurando el impacto sobre el blanco por muy rápido que sea.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=1000;
                $arma->clase=2;
                $arma->niveltec=28;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=180;
                $arma->nombre='Misil Xplasma';
                $arma->descripcion='Según nuestros científicos este arma usa unos principios tan avanzados que no merece la pena ser explicados, al fin y al cabo solo nos interesa la efectividad.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=800;
                $arma->clase=2;
                $arma->niveltec=29;
                $arma->malcance=3;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=201;
                $arma->nombre='MG ligero';
                $arma->descripcion='Mejorando las antiguas armas de las guerras planetarias hemos obtenido un arma muy sencilla, rápida y eficaz contra cazas, barata y con un alcance suficiente es a la vez un excelente arma defensiva para todo codigo de naves';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=100;
                $arma->clase=3;
                $arma->niveltec=2;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=202;
                $arma->nombre='MG pesada';
                $arma->descripcion='Siguiendo el mismo procedimiento para objetivos mas pequeños, para los mayores aumentamos el calibre de la munición, incorporamos cabezas perforantes y mejoramos el alcance, obteniendo un eficaz a bajo precio';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=400;
                $arma->clase=3;
                $arma->niveltec=3;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=203;
                $arma->nombre='Carga perforadora';
                $arma->descripcion='Para penetrar en los bunkers hemos desarrollado un arma de alta penetración que detona ha varias decenas de metros bajo la superficie';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=700;
                $arma->clase=3;
                $arma->niveltec=4;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=204;
                $arma->nombre='Cañón inercial';
                $arma->descripcion='Con una punta de alta densidad en proyectiles expulsados a velocidades supersónicas conseguimos penetrar los mejores blindajes y provocar una lluvia de material fundido en el interior del objetivo';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=400;
                $arma->clase=3;
                $arma->niveltec=5;
                $arma->malcance=1;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=205;
                $arma->nombre='Cañón Escila';
                $arma->descripcion='Basado en armas anteriores pero siguiendo un sistema multicañón y munición perforante, obtenemos un arma de gran cadencia de tiro contra objetivos blindados que asegura su acierto a base de un gasto considerable de munición';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=1500;
                $arma->clase=3;
                $arma->niveltec=6;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=206;
                $arma->nombre='Misil nuclear';
                $arma->descripcion='No hay mucho que contar de este arma, el sistema mas mortifero y eficaz de aniquilar todo en un amplio radio. Armando pequeños misiles con 5 kilotones obtenemos destrucción de pequeños objetivos en un radio amplio';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=1000;
                $arma->clase=3;
                $arma->niveltec=7;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=207;
                $arma->nombre='Artilleria pesada';
                $arma->descripcion='Aumentando el calibre y la potencia de los proyectibles se ha desarrollado la mayor pieza de artillería movil que se pueda contruir. El proyectil es ayudado por cohetes para corregir su trayectoria';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=7000;
                $arma->clase=3;
                $arma->niveltec=8;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=208;
                $arma->nombre='Carga antibunker';
                $arma->descripcion='Aplicando los principios aprendidos sobre destrucción de estructuras terrestres, podemos combinarlas en unas bombas inteligentes capaces de penetrar bajo tierra, perforar blindajes y detonar en el interior';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=4000;
                $arma->clase=3;
                $arma->niveltec=9;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=209;
                $arma->nombre='Misil interceptor';
                $arma->descripcion='Con una carga de racimo y un sistema de seguimiento perfeccionado, este misil es ideal para alcanzar y destruir a larga distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=800;
                $arma->clase=3;
                $arma->niveltec=10;
                $arma->malcance=2;
                $arma->dispersion=-3;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=211;
                $arma->nombre='Acelerador inercial';
                $arma->descripcion='Un proyectil acelerado magneticamente por un enorme cañon insertado para impactar como un meteorito sobre su objetivo, por desgracia su alcance y movilidad es limitado';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=100000;
                $arma->clase=3;
                $arma->niveltec=12;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=212;
                $arma->nombre='Multicañón';
                $arma->descripcion='Reduciendo los cañones pesados actuales obtenemos una versión menos potente pero devastadora a corta distancia, su incoveniente es el gran consumo de munición';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=3000;
                $arma->clase=3;
                $arma->niveltec=13;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=213;
                $arma->nombre='Artilleria orbital';
                $arma->descripcion='Disparar proyectiles directamente sobre los objetivos terrestres ayudados por la gravedad quizás sea la forma mas simple de causar daños';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=20000;
                $arma->clase=3;
                $arma->niveltec=14;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=214;
                $arma->nombre='Cañón Gauss';
                $arma->descripcion='Usando el mismo sistema magnético que en las armas insertadas, en menor tamaño obtenemos un cañon muy potente aunque limitado por la distancia por la dificultad de acertar a objetivos rápidos';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=15000;
                $arma->clase=3;
                $arma->niveltec=15;
                $arma->malcance=-1;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=215;
                $arma->nombre='Cañón municion MA';
                $arma->descripcion='Cargando un gran proyectil con un contenedor de Antimateria y propulsándolo magneticamente podemos conseguir un arma devastadora contra edificios que los desintegre practicamente de un disparo';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=55000;
                $arma->clase=3;
                $arma->niveltec=16;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=216;
                $arma->nombre='Minicañón Gauss';
                $arma->descripcion='Podemos miniaturizar tanto nuestra tecnología de impulsión magnética que obtenemos un cañon muy pequeño y eficiente, que combinado con los avances en munición nos da un arma ideal para cazas';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=1000;
                $arma->clase=3;
                $arma->niveltec=17;
                $arma->malcance=0;
                $arma->dispersion=-9;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=217;
                $arma->nombre='Cañón subespacial';
                $arma->descripcion='Si hacemos que un proyectil viaje por el hyperespacio durante una fraccion de segundo, evitamos todos los inconvenientes de alcanzar un objetivo rápido a mucha distancia, aunque es muy poco eficaz a corta distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=6000;
                $arma->clase=3;
                $arma->niveltec=18;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=219;
                $arma->nombre='Misil T-Cobalto';
                $arma->descripcion='Con una potente carga de tricobalto, este misil detona en las proximidades del objetivo distribuyendo gran cantidad de metralla de uranio empobrecido a alta velocidad';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=7000;
                $arma->clase=3;
                $arma->niveltec=20;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=220;
                $arma->nombre='Cañon super Gauss';
                $arma->descripcion='potenciando al maximo el acelerador de proyectiles gauss y usando las cargas de tricobalto, obtenemos un arma temible';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=10000;
                $arma->clase=3;
                $arma->niveltec=21;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=221;
                $arma->nombre='Bomba guiada TC';
                $arma->descripcion='Combinando nuestros conocimientos en misiles y las ultimas tecnologias en cargas explosivas, obtenemos un arma de bombardeo de muy larga distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=15000;
                $arma->clase=3;
                $arma->niveltec=22;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=222;
                $arma->nombre='Proyector subespacial';
                $arma->descripcion='Este arma está pensada como apoyo a otras, pese a su potencia por su precio es un complemento ideal';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=10000;
                $arma->clase=3;
                $arma->niveltec=23;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=223;
                $arma->nombre='MG hyperpesada';
                $arma->descripcion='Usando una serie de cañones rotativos que disparan balas a velocidad hyperespacial se pueden causar muchos daños a objetivos rapidos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=5000;
                $arma->clase=3;
                $arma->niveltec=24;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=224;
                $arma->nombre='Cañón DD';
                $arma->descripcion='Usando los viejos principios de cargas de metralla, este cañón dispara un haz de proyectiles de uranio emprobrecido que alcanzan una amplia zona aunque de poco alcance';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=2000;
                $arma->clase=3;
                $arma->niveltec=25;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=226;
                $arma->nombre='Misil Termita';
                $arma->descripcion='Cargado con sustancias corrosivas se detona antes de llegar al objetivo enviando un masa gelatinosa imposible de desviar, este misil es capaz de disolver en pocos minutos grandes masas de blindaje';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=10000;
                $arma->clase=3;
                $arma->niveltec=27;
                $arma->malcance=2;
                $arma->dispersion=-3;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=227;
                $arma->nombre='Cañon Mamut';
                $arma->descripcion='Usando la mas simple de las fuerzas brutas, con un enorme cañón con proyectiles cargados del mejor explosivo, este arma es capaz de perforar el mejor de los blindajes';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=8000;
                $arma->clase=3;
                $arma->niveltec=28;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=228;
                $arma->nombre='Proyector Mamut';
                $arma->descripcion='Es la versión pesada de un arma ya de por si brutal, especializada en demoler grandes estructuras aplicando simplemente masa y velocidad';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=12000;
                $arma->clase=3;
                $arma->niveltec=29;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=229;
                $arma->nombre='Detonador Omega';
                $arma->descripcion='Estas bombas utilizan la teoría del campo unificado para obtener toda la energía de la misma materia que destruyen en un proceso cíclico';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=20000;
                $arma->clase=3;
                $arma->niveltec=30;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=230;
                $arma->nombre='Cañón Hafnio';
                $arma->descripcion='Usando un isótopo de hafnio podemos hacer que cada bala explosiva sea una mini bomba nuclear.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=4000;
                $arma->clase=3;
                $arma->niveltec=31;
                $arma->malcance=3;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=231;
                $arma->nombre='Acelerador P';
                $arma->descripcion='Disparando partículas en vez de balas podemos generar una cantidad inmensa de partículas exóticas en la misma materia objetivo provocando todo codigos de efectos y desórdenes destructivos';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=4000;
                $arma->clase=3;
                $arma->niveltec=32;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=232;
                $arma->nombre='Cañón EX';
                $arma->descripcion='Los proyectiles disparados por este arma son de multipartículas exóticas lo que provoca descomposición radical en la materia con la que chocan sea cual sea el blindaje';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=10000;
                $arma->clase=3;
                $arma->niveltec=33;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=233;
                $arma->nombre='Bomba neutrón';
                $arma->descripcion='Este arma usa como proyectiles materia ultradensa de una estrella enana, generando un impacto demoledor';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=80000;
                $arma->clase=3;
                $arma->niveltec=34;
                $arma->malcance=0;
                $arma->dispersion=-3;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=235;
                $arma->nombre='Nanocañón';
                $arma->descripcion='En vez de usar proyectiles estandar, este arma proyecta millones de nano balas explosivas a velocidades cercanas a la luz que microfisuran cualquier blindaje haciendolo muy quebradizo ante el resto de armas';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=40000;
                $arma->clase=3;
                $arma->niveltec=36;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=236;
                $arma->nombre='Gyrojet';
                $arma->descripcion='Si cada bala es un misil inteligente en miniatura, podemos conseguir aceleraciones mayores para una precisión absoluta.';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=15000;
                $arma->clase=3;
                $arma->niveltec=37;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=237;
                $arma->nombre='Balas AI';
                $arma->descripcion='Avanzando mas en la tecnología de proyectiles se ha logrado un proyectil que se dispara y el sólo elige el punto más debil del enemigo y se dirige a él';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=5000;
                $arma->clase=3;
                $arma->niveltec=38;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=238;
                $arma->nombre='Bomba ET';
                $arma->descripcion='La misma integridad del espacio-tiempo con consecuencias impredecibles puede ser alterada con este arma, pero eso no es importante si logramos destruir al enemigo';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=100000;
                $arma->clase=3;
                $arma->niveltec=39;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=239;
                $arma->nombre='Cañón M';
                $arma->descripcion='Nuestras investigaciones en nanomateriales nos permiten hacer que los proyectiles cambien su forma y material en vuelo para adaptarse a las contramedidas enemigas';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=20000;
                $arma->clase=3;
                $arma->niveltec=40;
                $arma->malcance=1;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=251;
                $arma->nombre='Cañón MA';
                $arma->descripcion='Proyectando directamente Antimateria con un cañon, podemos provocar la anhiquilación de MA directamente en el objetivo';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=300;
                $arma->clase=4;
                $arma->niveltec=2;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=252;
                $arma->nombre='Minicañón MA';
                $arma->descripcion='Reduciendo el tamaño de un cañon MA obtenemos este arma, que aunque a primera vista parece poco optima, puede ser muy util en ciertas circunstancias';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=110;
                $arma->clase=4;
                $arma->niveltec=3;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=253;
                $arma->nombre='Bombas Antimateria';
                $arma->descripcion='Cargando antimateria en contenedores y mandándolos directamente sobre las estructuras terrestres provocamos la desintegración explosiva de grandes areas';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=500;
                $arma->clase=4;
                $arma->niveltec=4;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=254;
                $arma->nombre='Pulsar MA';
                $arma->descripcion='Emitiendo pulsos alternos de pártículas y antipartículas podemos provocar microfisuras extendidas en todo el casco de una nave, facilitando su destrucción por otras armas';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=3100;
                $arma->clase=4;
                $arma->niveltec=5;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=255;
                $arma->nombre='Torpedos de fotones';
                $arma->descripcion='Con una cabeza de MA, estos misiles son realmente mortíferos a corta distancia y son capaces además de provocar daños por radiacción a los enemigos cercanos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=2000;
                $arma->clase=4;
                $arma->niveltec=6;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=257;
                $arma->nombre='Percutor MA';
                $arma->descripcion='Este cañon insertado está diseñado para emitir cortas y constantes pulsaciones de antimateria, desmaterializando a la larga cualquier blindaje. Su inconveniente es la necesidad de un objetivo lento y grande';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=15000;
                $arma->clase=4;
                $arma->niveltec=8;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=258;
                $arma->nombre='Acelerador MA';
                $arma->descripcion='Acelerando la antimateria magneticamente, podemos proyectarla sobre objetivos medianamente blindados provocando la desintegración de una parte de su casco';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=4000;
                $arma->clase=4;
                $arma->niveltec=9;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=260;
                $arma->nombre='Inyector MA';
                $arma->descripcion='Con este arma introducimos átomos de antimateria en los blindajes enemigos mediante un haz magnético, lo que provoca su descomposión explosiva';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=1000;
                $arma->clase=4;
                $arma->niveltec=11;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=261;
                $arma->nombre='Cañón aniquilador';
                $arma->descripcion='Pensado sobretodo contra grandes naves, este cañón dotado de gran blindaje es la mejor forma de disuadir a cualquier atacante que quiera invadir nuestro planeta';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=13000;
                $arma->clase=4;
                $arma->niveltec=12;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=262;
                $arma->nombre='Disruptor MA';
                $arma->descripcion='Podemos detonar mucha antimateria en un punto provocando distorsiones indetectables en la estructura del espacio, así inumerables detonaciones pueden generar un campo lleno de distorsiones, especialmente eficaz contra naves pequeñas';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=250;
                $arma->clase=4;
                $arma->niveltec=13;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=264;
                $arma->nombre='Misil de Positrones';
                $arma->descripcion='Mediante la emisión masiva de un flujo de positrones generamos continuas y potentes reacciones de anhiquilación sobre los blindajes enemigos';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=4000;
                $arma->clase=4;
                $arma->niveltec=15;
                $arma->malcance=0;
                $arma->dispersion=0;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=265;
                $arma->nombre='Proyector MA';
                $arma->descripcion='Derivado de nuestras defensas MA, podemos provocar que parte de la materia de un objetivo se convierta en antimateria y detone directamente en el objetivo, su ventaja es la distancia pero solo permite objetivos lentos';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=15000;
                $arma->clase=4;
                $arma->niveltec=16;
                $arma->malcance=1;
                $arma->dispersion=3;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=266;
                $arma->nombre='Distorsionador espacial';
                $arma->descripcion='Generando un pulso de particulas Tau descomponemos la materia desde su estructura básica';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=3000;
                $arma->clase=4;
                $arma->niveltec=17;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=267;
                $arma->nombre='Emisor Nano MA';
                $arma->descripcion='Emitiendo nanopartículas con nucleo de antimateria podemos provocar la descomposición estructural de la materia desde el interior de las moléculas, deshaciendo cualquier material.';
                $arma->jugadores_id=1;
                $arma->ranura="armasBombas";
                $arma->potencia=1000;
                $arma->clase=4;
                $arma->niveltec=18;
                $arma->malcance=2;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=268;
                $arma->nombre='Onda gravitatoria';
                $arma->descripcion='La mejor forma de destruir objetivos rápidos y pequeños es emitir una onda de compresión gravitatoria que los aplaste';
                $arma->jugadores_id=1;
                $arma->ranura="armasMedias";
                $arma->potencia=3000;
                $arma->clase=4;
                $arma->niveltec=19;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=269;
                $arma->nombre='Proyector 0R';
                $arma->descripcion='Este arma minimiza a 0 la antimateria que rebota tras chocar con el objetivo, aumentando de forma radical la eficacia ante contramedidas u obstáculos';
                $arma->jugadores_id=1;
                $arma->ranura="armasInsertadas";
                $arma->potencia=25000;
                $arma->clase=4;
                $arma->niveltec=20;
                $arma->malcance=0;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=270;
                $arma->nombre='Acumulador MA';
                $arma->descripcion='Parte de la materia en el recorrido del proyectil es convertida tambien en antimateria, acumulando daños con al distancia';
                $arma->jugadores_id=1;
                $arma->ranura="armasMisiles";
                $arma->potencia=5000;
                $arma->clase=4;
                $arma->niveltec=21;
                $arma->malcance=0;
                $arma->dispersion=2;
                $arma->imagen="";
                array_push($armas, $arma);

                $arma =new Armas();
                $arma->codigo=271;
                $arma->nombre='Exo cañón';
                $arma->descripcion='Emitiendo antimateria exótica los efectos sobre el objetivo son siempre impredecibles pero devastadores';
                $arma->jugadores_id=1;
                $arma->ranura="armasLigeras";
                $arma->potencia=800;
                $arma->clase=4;
                $arma->niveltec=22;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


                $arma =new Armas();
                $arma->codigo=273;
                $arma->nombre='Cañón MAO';
                $arma->descripcion='Emitiendo antimateria oscura es mas dificil que nuestros adversarios puedan defenderse contra algo que apenas se conoce';
                $arma->jugadores_id=1;
                $arma->ranura="armasPesadas";
                $arma->potencia=10000;
                $arma->clase=4;
                $arma->niveltec=24;
                $arma->malcance=1;
                $arma->dispersion=1;
                $arma->imagen="";
                array_push($armas, $arma);


            foreach($armas as $estearma){
                $estearma->save();
            }

        //return $result;
    }






}